version: '3'
services: 
  dev-env: 
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    ports: 
      - "3000:3000" 
    volumes: 
      - /app/node_modules
      - ./:/app
    stdin_open: true
    tty: true
  # TODO add build service

  production:
    build:
      context: .
    ports:
      - "80:80"